### ISSUE TITLE
关于这本书是哪里来的？毛星云大佬的遗作吗？

### ISSUE THREAD

**Issue by weiyu666** [Morakito/Real-Time-Rendering-4th-CN#1]
你好~ RTR4中文版期盼已久，请问大佬这个是谁做的？
![image](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/22174508/785a1050-42dd-4247-bdbe-c0263dfad25d)
对于毛星云大佬之前的遭遇表示悲哀，哀叹！这个的PDF与MD文件看起来是要出书的稿，现在到底是怎么回事呀？请问现在还能出纸质版的书籍吗？如果可以出外面将会鼎力支持，争相购买~

**Comment by Morakito** [comment]
你好，这个是个人翻译的版本，用于学习交流，并非是毛星云前辈的版本或者官方版本。翻译工作前后用时一年，包括两次校对，其中可能还有一些问题，望批评指正，共同完成前辈的遗愿，为优秀国产游戏添砖加瓦。

**Comment by sjtuerx** [comment]
支持

**Comment by IWSR** [comment]
@Morakito 感谢佬的无私付出，同时也缅怀浅墨。

**Comment by liuke101** [comment]
感谢贡献

**Comment by byWH** [comment]
感谢

**Comment by Wangzhuanxu** [comment]
22岁就能翻译这本书，太厉害了

**Comment by zruibin** [comment]
大佬能否制作成epub格式的呢？pad上阅读起来更舒适

**Comment by Morakito** [comment]
@zruibin 暂时只有pdf文件和wolai在线文件（详见readme），pad上可以试试使用wolai进行阅读，也很方便。

**Comment by ThereAreBearsComing** [comment]
太叼了，大哥。这工作量❤

**Comment by kaclok** [comment]
感谢翻译此等宝典❤

**Comment by seulchanson** [comment]
序言有错别字，口袋里 “邻花钱”

**Comment by Morakito** [comment]
错别字已修正，wolai文件与markdown源文件已更新，谢谢指正！ @seulchanson

**Comment by maluonei** [comment]
第十章局部光照pdf版第32页，公式10.24的格式有点问题

**Comment by maluonei** [comment]
![QQ截图20231207210933](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/87125155/fe8cead5-4cb2-49bc-8585-88bc15671c67)

**Comment by Morakito** [comment]
已进行换行处理，wolai文件与markdown源文件已更新，PDF文件后续版本会进行统一更新，谢谢指正！
![image](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/53029790/042baa9f-ef78-48c3-8a7b-3df74daf90f0)
