### ISSUE TITLE
Chapter4公式勘误

### ISSUE THREAD

**Issue by xrunmasterx** [Morakito/Real-Time-Rendering-4th-CN#11]
Chapter4中4.12公式少了个负号

**Comment by Morakito** [comment]
Chapter 4中的equation 4.12符号typo已修正，wolai文件与markdown源文件已更新，谢谢指正！这下GitHub也是好友了
![image](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/53029790/9ee43709-de7b-4f4d-b92e-ee309996b438)
