### ISSUE TITLE
关于书中内容的一个疑惑

### ISSUE THREAD

**Issue by RickSchanze** [Morakito/Real-Time-Rendering-4th-CN#13]
在RTR4-CN第5.5.1节的末尾提到了一个under运算符，它的作用是让从前向后回合也可以得到与over运算符一样的结果。下面是它的公式：
![image](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/93311103/b1bc846e-b24a-43ae-92e1-8cdfecfcc38d)
注意到这里计算c0时，除以了a0，但是观察下面的几何图像解释，
![image](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/93311103/6bcc6e7b-158d-4502-984a-72f73517e86c)
zheli这里的a0代表了片元覆盖像素的面积，那么是否在公式5.26中，对a0的操作应该是乘呢？如图：
![image](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/93311103/84024390-521c-415e-9205-691723d3bdda)
我不知道这是否是一个笔误，希望您能为我解惑，万分感谢。

**Comment by Morakito** [comment]
您好，感谢您的思考和提问。关于这部分内容，可以参考以下资料：
1，RTR4勘误网站：其中提到结果颜色c0应该除以a0来补偿alpha覆盖率。
链接：https://www.realtimerendering.com/corrigenda.html 
2，维基百科：其中介绍了alpha合成的相关内容，这部分可以重点看一下。
链接：https://en.wikipedia.org/wiki/Alpha_compositing#Description
ps：修复了方程5.26中的typo，应为under operator

**Comment by RickSchanze** [comment]
感谢！链接里找到的一篇论文很好的解决我的疑惑，论文链接：https://graphics.stanford.edu/papers/merging-sig81/
