### ISSUE TITLE
1.2.1 下标错误

### ISSUE THREAD

**Issue by tomtc123** [Morakito/Real-Time-Rendering-4th-CN#14]
![image](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/3195882/2a93933d-056a-4b4a-a7f4-4848d504311c)
应该是**m22**

**Comment by Morakito** [comment]
1.2.1中的equation 1.1符号typo已修正，wolai文件与markdown源文件已更新，谢谢指正！
![image](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/53029790/c557c6da-43ee-414e-9854-9f72eaf8d6fd)
