### ISSUE TITLE
Chapter3 图 3.2 注释勘误

### ISSUE THREAD

**Issue by Zhao-Huazhou** [Morakito/Real-Time-Rendering-4th-CN#22]
图 3.2 注释原文中：“……黄色代表了这个阶段是可配置的，但并是非可编程的”，后半句中疑将“但并非是”误写为“但并是非”，提交勘误。
![QQ_1727597197021](https://github.com/user-attachments/assets/17d64a47-5915-4be0-b5dc-6e6e25bb0ae3)

**Comment by Morakito** [comment]
图3.2注释中的typo已修正，wolai文件与markdown源文件已更新，谢谢指正！
![image](https://github.com/user-attachments/assets/8366aff8-762e-47b3-a524-374c66b54046)
