### ISSUE TITLE
第四章三角函数公式有误？

### ISSUE THREAD

**Issue by yhyhdyb** [Morakito/Real-Time-Rendering-4th-CN#3]
![image](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/101050434/a0900f21-2711-4f13-bfed-c836aea85fc8)
sin的公式是不是加减号反了

**Comment by Morakito** [comment]
方程4.4已修正，wolai文件与markdown源文件已更新，谢谢指正！
![}M`CZY3)A0B{U4P`_2L8{MG](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/53029790/0099077f-11d1-4331-aab6-35f190b49c93)
