### ISSUE TITLE
chapter 1 简介第八页1.4式的符号错了

### ISSUE THREAD

**Issue by seedzy** [Morakito/Real-Time-Rendering-4th-CN#4]
![image](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/23522077/44e0f5fb-3fa6-47d8-abc4-69cdc8226274)
![image](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/23522077/3bac9440-bf4e-4136-93f1-6aee5c4b3d95)

**Comment by Morakito** [comment]
方程1.4已修正，wolai文件与markdown源文件已更新，谢谢指正！
