### ISSUE TITLE
6.2.6 图片注释错误

### ISSUE THREAD

**Issue by wilking131** [Morakito/Real-Time-Rendering-4th-CN#9]
![7YM8K6~X 28G_SDI(09RHVJ](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/87600084/53b31a50-2752-4c25-a5d6-35783d4e8dea)

**Comment by wilking131** [comment]
![image](https://github.com/Morakito/Real-Time-Rendering-4th-CN/assets/87600084/e9a29d7b-147c-40ca-a444-c8159ce882fb)
shunbianshuoy顺便说一句，这个6.1.1章节的这个uv之间用的中文逗号，虽然这严格来说算不上错，但是看起来怪怪的

**Comment by Morakito** [comment]
两处typo已修正，wolai文件与markdown源文件已更新，感谢反馈和指正！
